gbsim/loopback_test: add support for multiple modules
This patch adds support for multiple modules. It changes the method for
finding sysfs entries so that a user isn't forced to pass those values on
the command line. For each cport contained in a loopback test run we will
write a CSV line. So - if you have just one loopback cport you will get
one line in the CSV, if you have three loopback cports you will get three
lines in the CSV. We add a special CSV entry called 'aggregate_latency'.

aggregate_latency is the view of how long it took each each module to
perform one command in aggregate. In other words

t1 = gettime();
thread1:gb_sync_operation();
thread2:gb_sync_operation();
t2 = gettime();

In order to differentiate each entry in the CSV a new field has been added
'sysfs_entry' - this element in the CSV identifies which path in sysfs is
responsible for the data for each CSV line - so that the module, interface,
bundle and cport are apparent e.g. /sys/bus/greybus/devices/endo0:3:3:3:4

Format of the CSV file now will be

date:                         Datestamp of the test
type:                         ping, transfer or sink
sys_entry:                    Path to data source in the filesystem
size:                         Size of payload in bytes, ignored with ping
iteration_max:                The number of iterations for the test
error:                        Number of greybus operation errors
requests_per_second_min:      Minimum measured requests per second
requests_per_second_max:      Maximum measured requests per second
requests_per_second_avg:      Average measured requests per second
requests_per_second_jitter:   Jitter between min and max measured
                              requests per second
latency_min:                  Minimum measured latency
latency_max:                  Maximum measured latency
latency_avg:                  Average measured latency
latency_jitter:               Jitter between min and max latency
latency_gb_min:               Minimum measured greybus-only latency
latency_gb_max:               Maximum measured greybus-only latency
latency_gb_avg:               Average measured greybus-only latency
latency_gb_jitter:            Jitter between min and max greybus-only
                              latency
throughput_min:               Minimum measured bytes-per-second throughput
throughput_max:               Maximum measured bytes-per-second throughput
throughput_avg:               Average measured bytes-per-second throughput
thoughput_jitter:             Jitter between min and max measured
                              bytes-per-second throughput
raw_latencies:                1-iteration_max 32 bit numbers indicating
                              each individual greybus operation turn-around
                              time in microseconds

Signed-off-by: Bryan O'Donoghue <bryan.odonoghue@linaro.org>
Signed-off-by: Greg Kroah-Hartman <gregkh@google.com>